const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform, // 'win32' ou 'linux': o que só existe num dos dois some da tela
  getSources: () => ipcRenderer.invoke('get-sources'),
  selectSource: (id, withSystemAudio) => ipcRenderer.invoke('select-source', id, withSystemAudio),
  listAudioApps: () => ipcRenderer.invoke('list-audio-apps'),
  startAppAudio: (exes) => ipcRenderer.invoke('start-app-audio', exes),
  stopAppAudio: () => ipcRenderer.invoke('stop-app-audio'),
  onPcm: (cb) => ipcRenderer.on('pcm', (_e, data) => cb(data)),
  pipSetEdit: (on) => ipcRenderer.invoke('pip-edit', on),
  pipSize: (id, key) => ipcRenderer.invoke('pip-size', String(id), key),
  pipOpacity: (id, v) => ipcRenderer.invoke('pip-opacity', String(id), v),
  pipGroup: (id, patch) => ipcRenderer.invoke('pip-group', String(id), patch),
  roomKeys: (on) => ipcRenderer.invoke('room-keys', !!on),
  getShortcuts: () => ipcRenderer.invoke('get-shortcuts'),
  setShortcut: (action, accel) => ipcRenderer.invoke('set-shortcut', action, accel),
  ptt: (vk) => ipcRenderer.invoke('ptt', Number(vk) || 0),
  noiseWasm: (simd) => ipcRenderer.invoke('noise-wasm', !!simd),
  chatCompose: (on, opening = false) => ipcRenderer.invoke('chat-compose', !!on, !!opening),
  openLink: (url) => ipcRenderer.invoke('open-link', url),
  onPip: (cb) => {
    ipcRenderer.removeAllListeners('pip');
    ipcRenderer.on('pip', (_e, msg) => cb(msg));
  },
  videoCapProbe: () => ipcRenderer.invoke('videocap-probe'),
  videoCapStart: (opts) => ipcRenderer.invoke('videocap-start', opts),
  videoCapStop: () => ipcRenderer.invoke('videocap-stop'),
  videoCapCmd: (cmd) => ipcRenderer.invoke('videocap-cmd', cmd),
  onVideoCap: (onChunk, onStats, onEnded) => {
    for (const ch of ['vchunk', 'vstats', 'vended']) ipcRenderer.removeAllListeners(ch);
    ipcRenderer.on('vchunk', (_e, c) => onChunk(c));
    ipcRenderer.on('vstats', (_e, s) => onStats(s));
    ipcRenderer.on('vended', (_e, info) => onEnded(info));
  },
  offVideoCap: () => { for (const ch of ['vchunk', 'vstats', 'vended']) ipcRenderer.removeAllListeners(ch); },
  offPcm: () => ipcRenderer.removeAllListeners('pcm'),
  getIps: (provider) => ipcRenderer.invoke('get-ips', provider),
  copyText: (text) => ipcRenderer.invoke('copy-text', String(text || '')),
  razzePresence: () => ipcRenderer.invoke('razze-presence-state'),
  onRazzePresence: (callback) => { ipcRenderer.removeAllListeners('razze-presence'); ipcRenderer.on('razze-presence', (_event, value) => callback(value)); },
  razzeState: () => ipcRenderer.invoke('razze-state'),
  razzePendingInvite: () => ipcRenderer.invoke('razze-pending-invite'),
  onRazzeInvite: (callback) => {
    ipcRenderer.removeAllListeners('razze-invite');
    ipcRenderer.on('razze-invite', (_event, token) => callback(String(token || '')));
  },
  razzeConfigure: (url) => ipcRenderer.invoke('razze-configure', String(url || '')),
  razzeHealth: () => ipcRenderer.invoke('razze-health'),
  razzeMe: () => ipcRenderer.invoke('razze-me'),
  razzeRegister: (email, password, name) => ipcRenderer.invoke('razze-register', String(email || ''), String(password || ''), String(name || '')),
  razzeLogin: (email, password) => ipcRenderer.invoke('razze-login', String(email || ''), String(password || '')),
  razzeLogout: () => ipcRenderer.invoke('razze-logout'),
  razzeListNetworks: () => ipcRenderer.invoke('razze-list-networks'),
  razzeCreateNetwork: (network) => ipcRenderer.invoke('razze-create-network', network),
  razzeUpdateNetwork: (id, patch) => ipcRenderer.invoke('razze-update-network', String(id || ''), patch),
  razzeDeleteNetwork: (id) => ipcRenderer.invoke('razze-delete-network', String(id || '')),
  razzeAcceptInvite: (token) => ipcRenderer.invoke('razze-accept-invite', String(token || '')),
  razzeListMembers: (id) => ipcRenderer.invoke('razze-list-members', String(id || '')),
  razzeRemoveMember: (id, userId) => ipcRenderer.invoke('razze-remove-member', String(id || ''), String(userId || '')),
  razzeCreateInvite: (id, options) => ipcRenderer.invoke('razze-create-invite', String(id || ''), options),
  razzeFriends: () => ipcRenderer.invoke('razze-friends'),
  razzeFriendRequests: () => ipcRenderer.invoke('razze-friend-requests'),
  razzeRequestFriend: (email) => ipcRenderer.invoke('razze-request-friend', String(email || '')),
  razzeAcceptFriend: (id) => ipcRenderer.invoke('razze-accept-friend', String(id || '')),
  razzeRemoveFriend: (id) => ipcRenderer.invoke('razze-remove-friend', String(id || '')),
  razzeWireGuardStatus: (networkId) => ipcRenderer.invoke('razze-wg-status', String(networkId || '')),
  razzeWireGuardConnect: (networkId, name) => ipcRenderer.invoke('razze-wg-connect', String(networkId || ''), String(name || 'Razze')),
  razzeWireGuardDisconnect: (networkId) => ipcRenderer.invoke('razze-wg-disconnect', String(networkId || '')),
  razzeWireGuardDisconnectAll: () => ipcRenderer.invoke('razze-wg-disconnect-all'),
  razzeWireGuardResume: (networkId) => ipcRenderer.invoke('razze-wg-resume', String(networkId || '')),
  getVersion: () => ipcRenderer.invoke('get-version'),
  windowMaterial: (mode, color) => ipcRenderer.invoke('window-material', String(mode || ''), String(color || '')),
  setTitleBar: (color, symbolColor) => ipcRenderer.invoke('window-titlebar', String(color || ''), String(symbolColor || '')),
  setPriority: (level) => ipcRenderer.invoke('set-priority', level),
  statsStart: () => ipcRenderer.invoke('stats-start'),
  statsStop: () => ipcRenderer.invoke('stats-stop'),
  onStats: (cb) => ipcRenderer.on('stats', (_e, s) => cb(s)),
  offStats: () => ipcRenderer.removeAllListeners('stats'),
  getOwnPack: () => ipcRenderer.invoke('get-own-pack'),
  installUpdate: (pack, sig) => ipcRenderer.invoke('install-update', pack, sig),
  restartApp: () => ipcRenderer.invoke('restart-app'),
  githubCheck: () => ipcRenderer.invoke('github-check'),
  githubInstall: () => ipcRenderer.invoke('github-install'),
  openGithub: (url) => ipcRenderer.invoke('open-github', url),
  startServer: (port, password, seed, provider) => ipcRenderer.invoke('start-server', port, password, seed, provider),
  stopServer: (endRoom) => ipcRenderer.invoke('stop-server', !!endRoom),
  captureExclude: (on) => ipcRenderer.invoke('capture-exclude', !!on),
  // Sessões abertas na rede: escuta só com a tela inicial à vista
  sessoesObservar: (on) => ipcRenderer.invoke('sessoes-observar', !!on),
  onSessoes: (cb) => ipcRenderer.on('sessoes', (_e, lista) => cb(lista)),
});
